---
openapi: 3.1.0
info:
  title: 데모 프로젝트 API Document
  description: 데모 프로젝트의 API 명세서입니다.
  version: v0.0.1
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  "/loss-cases/{id}":
    get:
      tags:
      - loss-case-controller
      operationId: get
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/LossCase"
    put:
      tags:
      - loss-case-controller
      operationId: update
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/LossCase"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/LossCase"
    delete:
      tags:
      - loss-case-controller
      operationId: delete
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
  "/qna/questions":
    post:
      tags:
      - qna-controller
      operationId: addQuestion
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/QnaQ"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/QnaQ"
  "/qna/questions/{qId}/answers":
    get:
      tags:
      - qna-controller
      operationId: answers
      parameters:
      - name: qId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/QnaA"
    post:
      tags:
      - qna-controller
      operationId: addAnswer
      parameters:
      - name: qId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/AnswerReq"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/QnaA"
  "/loss-cases":
    get:
      tags:
      - loss-case-controller
      operationId: list
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/LossCase"
    post:
      tags:
      - loss-case-controller
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/LossCase"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/LossCase"
  "/chat/rooms":
    post:
      tags:
      - chat-controller
      operationId: createRoom
      parameters:
      - name: lossCaseId
        in: query
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/ChatRoom"
  "/chat/rooms/{roomId}/messages":
    get:
      tags:
      - chat-controller
      operationId: list_1
      parameters:
      - name: roomId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/ChatMessage"
    post:
      tags:
      - chat-controller
      operationId: updateMsg
      parameters:
      - name: roomId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/SendReq"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/ChatMessage"
  "/chat/rooms/{roomId}/close":
    post:
      tags:
      - chat-controller
      operationId: close
      parameters:
      - name: roomId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/ChatRoom"
components:
  schemas:
    LossCase:
      type: object
      properties:
        id:
          type: integer
          format: int64
        subject:
          type: string
          enum:
          - LOVER
          - PET
          - FRIEND
          - FAMILY
        withTime:
          type: string
          enum:
          - LESS_6M
          - M6_TO_1Y
          - Y1_TO_2Y
          - Y2_TO_5Y
          - Y5_TO_10Y
          - OVER_10Y
        lossDate:
          type: string
          format: date
        lossReason:
          type: string
          enum:
          - PARTNER_LOST_FEELINGS
          - I_LOST_FEELINGS
          - PERSONALITY_GAP
          - BETRAYAL
          - SITUATIONAL
          - UNKNOWN
        copeWay:
          type: string
          enum:
          - SUPPRESS
          - EXPRESS
          - AVOID
          - ANALYZE
        photo:
          type: string
          format: byte
        users:
          "$ref": "#/components/schemas/Users"
    Users:
      type: object
      properties:
        id:
          type: integer
          format: int64
        email:
          type: string
        pw:
          type: string
        name:
          type: string
        age:
          type: integer
          format: int32
        gender:
          type: string
    QnaQ:
      type: object
      properties:
        text:
          type: string
        lossCase:
          "$ref": "#/components/schemas/LossCase"
        qnaQId:
          type: integer
          format: int64
    AnswerReq:
      type: object
      properties:
        content:
          type: string
    QnaA:
      type: object
      properties:
        id:
          type: integer
          format: int64
        content:
          type: string
        qnaQ:
          "$ref": "#/components/schemas/QnaQ"
    ChatRoom:
      type: object
      properties:
        chatRoomId:
          type: integer
          format: int64
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        lossCase:
          "$ref": "#/components/schemas/LossCase"
    SendReq:
      type: object
      properties:
        sender:
          type: string
        text:
          type: string
    ChatMessage:
      type: object
      properties:
        id:
          type: integer
          format: int64
        sender:
          type: string
        text:
          type: string
        createdAt:
          type: string
          format: date-time
        chatRoom:
          "$ref": "#/components/schemas/ChatRoom"
